import Head from "next/head";
import Collage from "../components/Collage";
import Collage2 from "../components/Collage2";
import Collage3 from "../components/Collage3";
import End from "../components/End";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Media from "../components/Media";
import Navbar from "../components/Navbar";
import Poster from "../components/Poster";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ableton</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="max-w-[1600px]  mx-auto bg-white">
        <Navbar />
        <Header />
        <Collage />
        <Media />
        <Collage2 />
        <Poster />
        <Collage3 />
        <End />
        <Footer />
      </div>
    </div>
  );
}
